config/routes.rb
MovieDatabase::Application.routes.draw do
  resources :lists

  resources :movies do
    collection do
      get 'search'
    end
  end

  root :to => 'lists#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  attr_accessible :name
end

app/models/imdb.rb
module IMDB
  class Search
    def self.by_id(id)
      id = "tt#{id}"  unless id =~ /^tt/
      id_url = "http://imdbapi.org/?id=#{URI::escape id}&type=json&plot=simple&episode=0&lang=en-US&aka=simple&release=simple&business=0&tech=0"
      get_and_parse(id_url)
    end

    def self.by_title(title, options={})
      options[:limit] ||= 1
      
      title_url = "http://imdbapi.org/?title=#{URI::escape title}&type=json&plot=simple&episode=0&limit=#{options[:limit]}&yg=0&mt=none&lang=en-US&offset=&aka=simple&release=simple&business=0&tech=0"
      get_and_parse(title_url)
    end

    protected 

    def self.get_and_parse(url)
      JSON(RestClient.get(url))
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :color, :name

  has_many :movie_lists
  has_many :movies, through: :movie_lists
end

app/models/movie.rb
require 'imdb'

MovieNotFound  = Class.new(ArgumentError)

class Movie < ActiveRecord::Base
  attr_accessible :imdb_id, :title, :link, :poster_link, 
    :release_date, :director, :genres, :short_description

  has_many :movie_genres
  has_many :genres, through: :movie_genres

  has_many :movie_lists
  has_many :lists, through: :movie_lists
  
  validates_uniqueness_of :imdb_id
  validates :lists, length: { minimum: 1 }

  def self.search(param)
    ::IMDB::Search.by_title(param, { limit: 10 }).collect { |m| initialize_from_imdb(movie: m) }
  end

  # can optionally pass in the movie from IMDB already initialized (say from search by_title)
  def self.initialize_from_imdb(options={})
    their_movie = options[:movie] || ::IMDB::Search.by_id(options[:imdb_id])

    raise MovieNotFound  if their_movie['code'].try(:to_i).try(:>, 200)

    our_movie = new(
      imdb_id: their_movie['imdb_id'].rpartition('tt')[2],
      title: their_movie['title'],
      link: their_movie['imdb_url'],
      poster_link: their_movie['poster'],
      # release_date: their_movie['release_date'], # TODO remove release_date since IMDB API does not have this field
      director: Array(their_movie['directors']).first,
      short_description: their_movie['plot_simple']
    )

    Array(their_movie['genres']).collect do |g| 
      our_movie.genres.new(name: g.strip)
    end

    our_movie
  end

  def label
    "#{title}: #{short_description}"
  end
end

app/models/movie_genre.rb
class MovieGenre < ActiveRecord::Base
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_list.rb
class MovieList < ActiveRecord::Base
  belongs_to :movie
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def current_object_params
    @current_object_params ||= params[current_object_name]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = if params[:term].present?
      List.where("UPPER(name) like '%' || UPPER(?) || '%'", params[:term])
    else
      List.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists.collect { |l| { value: l.id, label: l.name } } }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
    @movies = @list.movies.sort { |a, b| a.title <=> b.title }
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.sort { |a, b| a.title <=> b.title }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # search for movies from IMDB, not our database
  def search
    @movies = Movie.search(params[:term]).collect do |movie|
      { label: movie.label, value: movie.imdb_id }
    end.compact

    respond_to do |format|  
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.initialize_from_imdb(imdb_id: current_object_params[:imdb_id])
    @movie.lists = current_object_params[:lists].strip.split(',').collect do |list_id| 
      List.find(list_id.strip)
    end

    respond_to do |format|
      if @movie.save
        format.html { redirect_to lists_path, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(current_object_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to @movie.lists.first }
      format.json { head :no_content }
    end
  end

  protected

  def current_object_name
    :movie
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDatabase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.name %></td>
    <td><%= list.color %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'New List', new_list_path %>
<%= link_to 'Show All Movies', movies_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <b>Name:</b>
  <%= @list.name %>
</p>


<% @movies.each_with_index do |movie, index| -%>
<p>
  <%= index + 1 %>: <%= movie.title %>&nbsp;&nbsp;&nbsp;
  <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<% end -%>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imdbd_id, "Movie (Autocomplete)" %><br />
    <%= f.text_field :imdb_id %>
  </div>
  <div class="field">
    <%= f.label :lists, "Lists (Autocomplete)" %><br />
    <%= f.text_field :lists, value: nil %>
  </div>
  <div class="actions">
    <%= f.submit "Add Movie to Library" %>
  </div>
<% end %>

<%= javascript_tag do -%>
$(function() {
  function split( val ) {
    return val.split( /,\s*/ );
  }

  function extractLast( term ) {
    return split( term ).pop();
  }
  <%# autocomplete the Imdb ID by searching the 
      Imdb database for the keywords typed in the Imdb ID text box %>
  $('#movie_imdb_id').autocomplete({
    source: '<%= search_movies_path(format: 'json') %>',
    minLength: 4,
    delay: 500
  })

  <%# autocomplete the multiselect of lists %>
  $( "#movie_lists" )
    // don't navigate away from the field on tab when selecting an item
    .bind( "keydown", function( event ) {
      if ( event.keyCode === $.ui.keyCode.TAB &&
          $( this ).data( "ui-autocomplete" ).menu.active ) {
        event.preventDefault();
      }
    })
    .autocomplete({
      source: function( request, response ) {
        console.debug("SOURCE")
        $.getJSON( '<%= lists_path(format: 'json') %>', {
          term: extractLast( request.term )
        }, response );
      },
      search: function() {
        // custom minLength
        console.debug("SEARCH")
        var term = extractLast( this.value );
        if ( term.length < 1 ) {
          return false;
        }
      },
      focus: function() {
        // prevent value inserted on focus
        return false;
      },
      select: function( event, ui ) {
        var terms = split( this.value );
        // remove the current input
        terms.pop();
        // add the selected item
        terms.push( ui.item.value );
        // add placeholder to get the comma-and-space at the end
        terms.push( "" );
        this.value = terms.join( ", " );
        return false;
      }
    });
});
<% end -%>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= link_to 'More Info', movie.link, target: '_blank' %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'Show All Lists', lists_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>